CREATE TABLE WOS_14_16_NORM AS (
SELECT
    t1.PK_ITEMS,
    LOWER(TRIM(DOI)) AS DOI,
    PUBYEAR,
    LOWER(t1.DOCTYPE) AS ARTICLE_TYPE,
    LOWER(TRIM(ARTICLE_TITLE)) AS ARTICLE_TITLE,
    AUTHOR_CNT AS AUTHORCOUNT,
    LOWER(TRIM(SOURCETITLE)) AS JOURNAL_NAME,
    ISSN AS JOURNAL_ISSNS
FROM
    WOS_B_2018.ITEMS t1
INNER JOIN
    WOS_B_2018.SOURCES t2
ON
    t1.FK_SOURCES = t2.PK_SOURCES
    AND t1.PUBYEAR >= 2014
    AND t1.PUBYEAR <= 2016)