SELECT 
    ROUND(SUM(CASE WHEN t1.TITLE = t2.ARTICLE_TITLE THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS PCT_EXACT_TITLE_MATCHES
FROM
    GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 t1
INNER JOIN
    WOS_B_2019.ITEMS t2
ON
    t1.DOI = t2.DOI AND
    t1.GENRE = 'journal-article' AND
    t2.DOCTYPE IN ('Article', 'Review')
    AND t2.PUBYEAR >= 2014
    AND t2.PUBYEAR <= 2016