SELECT 
    UTL_MATCH.EDIT_DISTANCE_SIMILARITY(LOWER(TRIM(t1.TITLE)),LOWER(TRIM(t2.ARTICLE_TITLE))) AS EDIT_DISTANCE_SIMILARITY, 
    UTL_MATCH.JARO_WINKLER_SIMILARITY(LOWER(TRIM(t1.TITLE)),LOWER(TRIM(t2.ARTICLE_TITLE))) AS JARO_WINKLER_SIMILARITY
FROM
    GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 SAMPLE(1) t1
INNER JOIN
    WOS_B_2019.ITEMS t2
ON
    t1.DOI = t2.DOI
    AND t1.GENRE = 'journal-article'
    AND t2.DOCTYPE IN ('Article', 'Review')
    AND t2.PUBYEAR >= 2014
    AND t2.PUBYEAR <= 2016