SELECT
    LENGTH_DIFFERENCE, COUNT(*) AS N
FROM (
    SELECT
        ABS(LENGTH(t1.TITLE)-LENGTH(t2.ARTICLE_TITLE)) AS LENGTH_DIFFERENCE 
    FROM
        GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 t1
    INNER JOIN
        WOS_B_2019.ITEMS t2
    ON
        t1.DOI = t2.DOI 
        AND t1.GENRE = 'journal-article' 
        AND t2.DOCTYPE IN ('Article', 'Review')
        AND t2.PUBYEAR >= 2014
        AND t2.PUBYEAR <= 2016
    )
GROUP BY LENGTH_DIFFERENCE
ORDER BY LENGTH_DIFFERENCE
