WITH WOS_SAMPLE AS(
    SELECT 
        LOWER(TRIM(ARTICLE_TITLE)) AS WOS_TITLE 
    FROM 
        WOS_B_2019.ITEMS SAMPLE(0.01) 
    WHERE 
        DOCTYPE IN ('Article', 'Review')
        AND PUBYEAR >= 2014
        AND PUBYEAR <= 2016
),
UNPAYWALL_SAMPLE AS(
    SELECT 
        LOWER(TRIM(TITLE)) AS UNPAYWALL_TITLE 
    FROM 
        GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 SAMPLE(0.01)
    WHERE
        GENRE = 'journal-article'
)
SELECT 
    UTL_MATCH.EDIT_DISTANCE_SIMILARITY(WOS_TITLE, UNPAYWALL_TITLE) AS EDIT_DISTANCE_SIMILARITY, 
    UTL_MATCH.JARO_WINKLER_SIMILARITY(WOS_TITLE, UNPAYWALL_TITLE) AS JARO_WINKLER_SIMILARITY
FROM 
    WOS_SAMPLE
CROSS JOIN 
    UNPAYWALL_SAMPLE