SELECT 
    LOWER(TRIM(ARTICLE_TITLE)) AS ARTICLE_TITLE, COUNT(*) AS N
FROM 
    WOS_B_2019.ITEMS
WHERE
    DOCTYPE IN ('Article', 'Review')
    AND PUBYEAR >= 2014
    AND PUBYEAR <= 2016
    AND ARTICLE_TITLE IS NOT NULL
GROUP BY LOWER(TRIM(ARTICLE_TITLE))
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC
FETCH FIRST 100 ROWS ONLY
