SELECT 
    ROUND(SUM(CASE WHEN t1.D_AUTHOR_CNT = t2.AUTHORCOUNT THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS PCT_EXACT_AUTHORCOUNT_MATCHES
FROM 
  WOS_B_2019.ITEMS t1
INNER JOIN 
  GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 t2
ON
  t1.DOI = t2.DOI
  AND t2.GENRE = 'journal-article'
  AND t1.DOCTYPE IN ('Article', 'Review')
  AND PUBYEAR >= 2014
  AND PUBYEAR <= 2016
  