SELECT 
    ROUND(SUM(CASE WHEN t2.ISSN LIKE t4.ISSN THEN 1 ELSE 0 END)/COUNT(DISTINCT t1.DOI)*100,2) AS PCT_EXACT_ISSN_MATCHES
FROM 
  WOS_B_2019.ITEMS t1
INNER JOIN
  WOS_B_2019.SOURCES t2
ON
  t1.FK_SOURCES = t2.PK_SOURCES
  AND t1.DOCTYPE IN ('Article', 'Review')
  AND t1.PUBYEAR >= 2014
  AND t1.PUBYEAR <= 2016
INNER JOIN
  GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 t3
ON
  t1.DOI = t3.DOI
  AND t3.GENRE = 'journal-article'
LEFT JOIN
  GWDGAHOBERT.UPW_14_NORM_ISSNS t4
ON
  t3.DOI = t4.DOI