SELECT 
  ROUND(SUM(CASE WHEN LOWER(TRIM(t3.JOURNAL_NAME)) = LOWER(TRIM(t2.SOURCETITLE)) THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS PCT_EXACT_JOURNAL_MATCHES
FROM 
  WOS_B_2019.ITEMS t1
INNER JOIN
  WOS_B_2019.SOURCES t2
ON
  t1.FK_SOURCES = t2.PK_SOURCES
  AND t1.DOCTYPE IN ('Article', 'Review')
  AND t1.PUBYEAR >= 2014
  AND t1.PUBYEAR <= 2016
INNER JOIN
  GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 t3
ON
  t1.DOI = t3.DOI
  AND t3.GENRE = 'journal-article'