SELECT
    COUNT(*) AS MATCHES, t1.YEAR AS UNPAYWALL_YEAR, t2.PUBYEAR AS WOS_YEAR
FROM
    GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14 t1
INNER JOIN
    WOS_B_2019.ITEMS t2
ON
    t1.DOI = t2.DOI
    AND t1.GENRE = 'journal-article'
    AND t2.DOCTYPE IN ('Article', 'Review')
GROUP BY t1.YEAR, t2.PUBYEAR