CREATE TABLE WOS_12_17_AUTHORNAMES AS (
SELECT DISTINCT
    t1.PK_ITEMS, t1.DOI, t1.AUTHORCOUNT, 'first' AS AUTHOR_POSITION,
    LOWER(TRIM(t3.FIRSTNAME)) AS FIRSTNAME,
    LOWER(TRIM(t3.LASTNAME)) AS LASTNAME,
    CONCAT(LOWER(SUBSTR(t3.FIRSTNAME, 1, 1)), LOWER(SUBSTR(t3.LASTNAME, 1, 1))) AS INITIALS,
    CONCAT(LOWER(REGEXP_REPLACE(t3.LASTNAME, '[^A-Za-z]','')), LOWER(substr(t3.FIRSTNAME, 1, 1))) AS BLOCKED_NAME
FROM
   WOS_12_17_NORM t1
INNER JOIN
   WOS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t2
ON
    t1.PK_ITEMS = t2.FK_ITEMS
INNER JOIN
    WOS_B_2018.AUTHORS t3
ON
    t2.FK_AUTHORS = t3.PK_AUTHORS
    AND (t2.AUTHOR_POSITION = 1)
UNION
SELECT DISTINCT
    t1.PK_ITEMS, t1.DOI, t1.AUTHORCOUNT, 'last' AS AUTHOR_POSITION,
    LOWER(TRIM(t3.FIRSTNAME)) AS FIRSTNAME,
    LOWER(TRIM(t3.LASTNAME)) AS LASTNAME,
    CONCAT(LOWER(SUBSTR(t3.FIRSTNAME, 1, 1)), LOWER(SUBSTR(t3.LASTNAME, 1, 1))) AS INITIALS,
    CONCAT(LOWER(REGEXP_REPLACE(t3.LASTNAME, '[^A-Za-z]','')), LOWER(substr(t3.FIRSTNAME, 1, 1))) AS BLOCKED_NAME
FROM
   WOS_12_17_NORM t1
INNER JOIN
   WOS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t2
ON
    t1.PK_ITEMS = t2.FK_ITEMS
INNER JOIN
    WOS_B_2018.AUTHORS t3
ON
    t2.FK_AUTHORS = t3.PK_AUTHORS
    AND (t2.AUTHOR_POSITION = t1.AUTHORCOUNT));