CREATE TABLE UPW_14_TITLE_BLACKLIST AS (SELECT
    ARTICLE_TITLE, COUNT(*) AS N
FROM
    GESISNFRASER.UPW_14_NORM
WHERE
    ARTICLE_TYPE = 'journal-article'
GROUP BY
    ARTICLE_TITLE
HAVING
    COUNT(*) > 1);
    
CREATE TABLE WOS_12_17_TITLE_BLACKLIST AS (
SELECT
    ARTICLE_TITLE, COUNT(*) AS N
FROM
    GESISNFRASER.WOS_12_17_NORM
WHERE
    ARTICLE_TYPE IN ('article', 'review')
GROUP BY
    ARTICLE_TITLE
HAVING
    COUNT(*) > 1);