CREATE TABLE FIRST_AUTHOR_NAMES_WOS14 AS (SELECT DISTINCT
    t1.PK_ITEMS, t1.DOI, CONCAT(lower(regexp_replace(t3.LASTNAME, '[^A-Za-z]','')), lower(substr(t3.FIRSTNAME, 1, 1))) AS AUTHORNAME
FROM
   WOS_B_2018.ITEMS t1
INNER JOIN
   WOS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t2
ON
    t1.PK_ITEMS = t2.FK_ITEMS
    AND t1.PUBYEAR = 2014
INNER JOIN
    WOS_B_2018.AUTHORS t3
ON
    t2.FK_AUTHORS = t3.PK_AUTHORS
    AND AUTHOR_POSITION = 1)