SELECT DISTINCT
    t1.PK_ITEMS, t1.DOI, 
    CASE WHEN t2.AUTHOR_POSITION = 1 THEN 'first'
         WHEN t2.AUTHOR_POSITION = t1.AUTHOR_CNT THEN 'last' END AS AUTHOR_POSITION
    LOWER(TRIM(t3.FIRSTNAME)) AS FIRSTNAME,
    LOWER(TRIM(t3.LASTNAME)) AS LASTNAME,
    CONCAT(substr(t3.FIRSTNAME, 1, 1), LOWER(substr(t3.LASTNAME, 1, 1))) AS INITIALS,
    CONCAT(LOWER(REGEXP_REPLACE(t3.LASTNAME, '[^A-Za-z]','')), LOWER(substr(t3.FIRSTNAME, 1, 1))) AS BLOCKED_NAME
FROM
   WOS_B_2018.ITEMS t1
INNER JOIN
   WOS_B_2018.ITEMS_AUTHORS_INSTITUTIONS t2
ON
    t1.PK_ITEMS = t2.FK_ITEMS
    AND t1.PUBYEAR = 2014
INNER JOIN
    WOS_B_2018.AUTHORS t3
ON
    t2.FK_AUTHORS = t3.PK_AUTHORS
    AND (t2.AUTHOR_POSITION = 1 OR t2.AUTHOR_POSITION = t1.AUTHOR_CNT)