SELECT
    COUNT(*) AS MATCHES, t1.ARTICLE_TYPE AS UNPAYWALL_TYPE, t2.ARTICLE_TYPE AS WOS_TYPE
FROM
    UPW_14_NORM t1
INNER JOIN
    WOS_12_17_NORM t2
ON
    t1.DOI = t2.DOI
GROUP BY t1.ARTICLE_TYPE, t2.ARTICLE_TYPE