SELECT 
    ROUND(SUM(CASE WHEN t2.ISSN_VALUE = t3.JOURNAL_ISSNS THEN 1 ELSE 0 END)/COUNT(DISTINCT t1.DOI)*100,2) AS PCT_EXACT_ISSN_MATCHES
FROM
    UPW_14_NORM t1
LEFT JOIN
    UPW_14_NORM_ISSNS t2
ON
    t1.DOI = t2.DOI
INNER JOIN
    WOS_12_17_NORM t3
ON
    t1.DOI = t3.DOI AND
    t1.ARTICLE_TYPE = 'journal-article'
    AND t3.ARTICLE_TYPE IN ('article', 'review')