SELECT 
    UTL_MATCH.EDIT_DISTANCE_SIMILARITY(t1.ARTICLE_TITLE,t2.ARTICLE_TITLE) AS EDIT_DISTANCE_SIMILARITY, 
    UTL_MATCH.JARO_WINKLER_SIMILARITY(t1.ARTICLE_TITLE, t2.ARTICLE_TITLE) AS JARO_WINKLER_SIMILARITY
FROM
    UPW_14_NORM SAMPLE(5) t1
INNER JOIN
    WOS_12_17_NORM t2
ON
    t1.DOI = t2.DOI