SELECT 
    COUNT(*) AS TOTAL_MATCHES, 
    COUNT(DISTINCT t2.DOI) AS DISTINCT_WOS_DOIS, 
    COUNT(DISTINCT t2.PK_ITEMS) AS DISTINCT_WOS_PK_ITEMS,
    COUNT(DISTINCT t1.DOI) AS DISTINCT_UNPAYWALL_DOIS
FROM
    GESISNFRASER.UPW_14_NORM t1
INNER JOIN
    GESISNFRASER.WOS_12_17_NORM t2
ON
    t1.DOI = t2.DOI