SELECT 
    COUNT(*) AS MATCHES, t1.AUTHORCOUNT AS UNPAYWALL_AUTHORS, t2.AUTHORCOUNT AS WOS_AUTHORS
FROM
    UPW_14_NORM t1
INNER JOIN
    WOS_12_17_NORM t2
ON
    t1.DOI = t2.DOI
    AND t1.ARTICLE_TYPE = 'journal-article'
    AND t2.ARTICLE_TYPE in ('article', 'review')
GROUP BY t1.AUTHORCOUNT, t2.AUTHORCOUNT