CREATE TABLE UPW_14_NORM AS (
SELECT
    LOWER(TRIM(DOI)) AS DOI,
    YEAR AS PUBYEAR,
    LOWER(GENRE) AS ARTICLE_TYPE,
    LOWER(TRIM(TITLE)) AS ARTICLE_TITLE,
    AUTHORCOUNT,
    CONCAT(LOWER(TRIM(REGEXP_REPLACE(AUTHOR_FIRST_FAMILY, '[^A-Za-z]',''))), LOWER(SUBSTR(TRIM(AUTHOR_FIRST_GIVEN), 1, 1))) AS FIRST_AUTHOR_NAME,
    CONCAT(LOWER(TRIM(REGEXP_REPLACE(AUTHOR_LAST_FAMILY, '[^A-Za-z]',''))), LOWER(SUBSTR(TRIM(AUTHOR_LAST_GIVEN), 1, 1))) AS LAST_AUTHOR_NAME,
    LOWER(TRIM(JOURNAL_NAME)) AS JOURNAL_NAME,
    JOURNAL_ISSNS
FROM
    GWDGAHOBERT.UPW_APR19_MATCHINGTEST_14)
    
