SELECT
    DIFF, COUNT(*)
FROM (
    SELECT
        ABS(LENGTH(t1.ARTICLE_TITLE)-LENGTH(t2.ARTICLE_TITLE)) AS DIFF 
    FROM
        UPW_14_NORM SAMPLE(0.01) t1
    CROSS JOIN
        WOS_12_17_NORM SAMPLE(0.01) t2)
GROUP BY DIFF
ORDER BY DIFF
