WITH WOS_SAMPLE AS(
    SELECT ARTICLE_TITLE AS WOS_TITLE FROM WOS_12_17_NORM SAMPLE(0.001)
),
UNPAYWALL_SAMPLE AS(
    SELECT ARTICLE_TITLE AS UNPAYWALL_TITLE FROM UPW_14_NORM SAMPLE(0.01)
)
SELECT 
    UTL_MATCH.EDIT_DISTANCE_SIMILARITY(WOS_TITLE, UNPAYWALL_TITLE) AS EDIT_DISTANCE_SIMILARITY, 
    UTL_MATCH.JARO_WINKLER_SIMILARITY(WOS_TITLE, UNPAYWALL_TITLE) AS JARO_WINKLER_SIMILARITY
FROM 
    WOS_SAMPLE
CROSS JOIN 
    UNPAYWALL_SAMPLE